version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm i aos
      - npm install material.ui
  build:
    commands:
      - ls
      - echo Build started on 'date'
      - npm run build
artifacts:
  files:
    - '**/*'
    #- "my-app/build/**/*"
  base-directory: '/dist'
  #discard-paths: yes