
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - ls
      - echo Build started on 'date'
      - npm run build
artifacts:
  files:
    - '**/*'
    #- "my-app/build/**/*"
  base-directory: '/'
  #discard-paths: yes
